# Building  Predictive Models

In [1]:
import pandas as pd
import os
import numpy as np

### Import data

In [2]:
# set path of processed data 

processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [3]:
train_df = pd.read_csv(train_file_path, index_col='PassengerId')
test_df = pd.read_csv(test_file_path, index_col='PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

### Data Preparation

In [5]:
X = train_df.loc[:,'Age':].as_matrix().astype('float')
y = train_df['Survived'].ravel()

In [6]:
print X.shape, y.shape

(891L, 32L) (891L,)


In [7]:
# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(712L, 32L) (712L,)
(179L, 32L) (179L,)


In [11]:
# Avg survival in train and test 
print 'mean/avg survival in train: {0:.3f}'.format(np.mean(y_train))
print 'mean/avg survival in test: {0:.3f}'.format(np.mean(y_test))

mean/avg survival in train: 0.383
mean/avg survival in test: 0.385


##### Check Scikit_learn Version

In [8]:
import sklearn

In [11]:
sklearn.__version__

'0.19.1'

In [12]:
# Scikit-leran 0.19+ / also !conda update -y scikit-learn

#### Baseline model

In [9]:
# import fucntion
from sklearn.dummy import DummyClassifier

In [13]:
#create model
model_dummy = DummyClassifier(strategy='most_frequent', random_state=0)

In [14]:
#train model
model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [15]:
print 'score of baseline model: {0:.2f}'.format(model_dummy.score(X_test, y_test))

score of baseline model: 0.61


In [22]:
# prefformance metrics
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [17]:
# accuracy score 
print 'accuracy for baseline mode: {0:.2f}'.format(accuracy_score(y_test, model_dummy.predict(X_test)))

accuracy for baseline mode: 0.61


In [18]:
# confusion matrix
print 'confusion matrix for baseline mode: \n {0}'.format(confusion_matrix(y_test, model_dummy.predict(X_test)))

confusion matrix for baseline mode: 
 [[110   0]
 [ 69   0]]


In [20]:
#precision and recal score 
print 'precison for baseline mode: {0:.2f}'.format(precision_score(y_test, model_dummy.predict(X_test)))
print 'recall for baseline mode: {0:.2f}'.format(recall_score(y_test, model_dummy.predict(X_test)))

precison for baseline mode: 0.00
recall for baseline mode: 0.00


E:\Anaconda2\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


#### Kaggle Submission

In [11]:
# converting to the matrix
test_X = test_df.as_matrix().astype('float')

In [19]:
#get predictions
predictions = model_dummy.predict(test_X)

In [20]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived': predictions})

In [21]:
df_submission.tail(15)

PassengerId  Survived
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         0
409         1301         0
410         1302         0
411         1303         0
412         1304         0
413         1305         0
414         1306         0
415         1307         0
416         1308         0
417         1309         0

In [25]:
submission_data_path = os.path.join(os.path.pardir,'data','external')
submission_file_path = os.path.join(submission_data_path,'01_dummy.csv')

In [26]:
df_submission.to_csv(submission_file_path, index=False)

In [27]:
def get_submission_file(model, filename):
    # conver to the matrix
    test_X = test_df.as_matrix().astype('float')
    # make predictions
    predictions = model.predict(test_X)
    # submission dataframe
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived' : predictions})
    # submission file
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path, filename)
    # write to teh file
    df_submission.to_csv(submission_file_path, index=False)

In [28]:
# get submission file
get_submission_file(model_dummy, '01_dummy.csv')

### Logistic Regresion Model

In [12]:
# import function 
from sklearn.linear_model import LogisticRegression

In [13]:
# create model
model_lr_1 = LogisticRegression(random_state=0)

In [17]:
# train model
model_lr_1.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
# evaluate model 
print 'score for logistic regression - version 1: {0:.2f}'.format(model_lr_1.score(X_test, y_test))

score for logistic regression - version 1: 0.83


In [23]:
print 'accuracy for logistic regression: {0:.2f}'.format(accuracy_score(y_test, model_lr_1.predict(X_test)))
print 'confusion matrix for logistic regression: \n {0}'.format(confusion_matrix(y_test, model_lr_1.predict(X_test)))
print 'precison for logistic regression: {0:.2f}'.format(precision_score(y_test, model_lr_1.predict(X_test)))
print 'recall for logistic regression: {0:.2f}'.format(recall_score(y_test, model_lr_1.predict(X_test)))

accuracy for logistic regression: 0.83
confusion matrix for logistic regression: 
 [[95 15]
 [15 54]]
precison for logistic regression: 0.78
recall for logistic regression: 0.78


In [24]:
# model coefficients
model_lr_1.coef_

array([[-0.02842272,  0.00455452, -0.50009091,  0.61781316, -0.8139233 ,
         0.12845079, -0.17281789, -0.39317833,  0.52159977,  1.09941224,
         0.40341217, -0.18345051, -0.30036042,  0.96533486,  0.48256743,
        -0.34483447,  0.28089593,  1.21761327,  0.56363966, -1.44586304,
         1.07245552, -0.11273706, -0.47293647,  0.16255646,  0.24716929,
         0.28009437,  0.4132477 ,  0.49183529,  0.46198829,  0.14924424,
         0.37283517,  0.73023265]])

In [21]:
# Kaggle resub new numbers
get_submission_file(model_lr_1, '02_lr.csv')

NameError: name 'get_submission_file' is not defined

### Hyperparameter Optimatization

In [25]:
# base model 
model_lr = LogisticRegression(random_state=0)

In [26]:
from sklearn.model_selection import GridSearchCV

In [27]:
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3) # cv = crossvalidation

In [28]:
clf.fit(X_train,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [23]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [29]:
print 'best score: {0:.2f}'.format(clf.best_score_)

best score: 0.83


In [30]:
# Evalute model
print 'score of LR - version 2 : {0:.2f}'.format(clf.score(X_test,y_test))

score of LR - version 2 : 0.83


In [48]:
get_submission_file(clf,'03_lr.csv')

In [49]:
print 'precison for logistic regression: {0:.2f}'.format(precision_score(y_test, clf.predict(X_test)))

precison for logistic regression: 0.77


#### Feature Normalization and Standarization

In [31]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [59]:
###### Feature Normalization ######
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [60]:
X_train_scaled[:,0].min(),X_train_scaled[:,0].max()

(0.0, 1.0)

In [61]:
# normalized test data
X_test_scaled = scaler.transform(X_test)

##### Feature Standarization 

In [62]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

###### Create model after standarization

In [63]:
# base model
model_lr = LogisticRegression(random_state=0)
parameters = {'C':[1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty' : ['l1','l2']}
clf = GridSearchCV(model_lr, param_grid=parameters, cv=3)
clf.fit(X_train_scaled, y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [64]:
clf.best_score_

0.8132022471910112

In [71]:
print 'score for LR - ver. 2.1: {0:.2f}'.format(clf.score(X_test_scaled, y_test))

score for LR - ver. 2.1: 0.84


#### Model presistence

In [81]:
# import pickle
import pickle

In [82]:
# create file paths
model_file_path = os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path = os.path.join(os.path.pardir,'models','lr_scaler.pkl')

In [83]:
# open files to write
model_file_pickle = open(model_file_path, 'wb')
scaler_file_pickle = open(scaler_file_path, 'wb')

In [84]:
# persist the model and scaler 
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler, scaler_file_pickle)

In [85]:
# close the file
model_file_pickle.close()
scaler_file_pickle.close()

##### load the persisted file

In [86]:
# open files i read 'r' mode 
model_file_pickle = open(model_file_path, 'r')
scaler_file_pickle = open(scaler_file_path, 'r')
# load files
clf_loaded = pickle.load(model_file_pickle)
scaler_loaded = pickle.load(scaler_file_pickle)
# close files
model_file_pickle.close()
scaler_file_pickle.close()

                         

In [87]:
clf_loaded

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1.0, 10.0, 50.0, 100.0, 1000.0]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [88]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [92]:
# trasform the test that using loaded scaler object
X_test_scaled = scaler_loaded.transform(X_test)
# calculate the score using loaded model object 
print 'score presisted LR : {0:.2f}'.format(clf_loaded.score(X_test_scaled,y_test))

score presisted LR : 0.84
